# Generated by Django 3.0.4 on 2020-04-09 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0002_auto_20200408_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='email',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
