# Generated by Django 3.0.4 on 2020-04-09 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0003_influencer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='password',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
