# Generated by Django 3.0.4 on 2020-04-11 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0005_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='documents/%Y/%m/%d')),
            ],
        ),
    ]
