# Generated by Django 3.0.4 on 2020-04-15 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0007_auto_20200412_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencer',
            name='facebook',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='instagram',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='twitter',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='youtube',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
