# Generated by Django 3.0.4 on 2020-04-20 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0008_auto_20200415_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.ImageField(upload_to='documents/'),
        ),
    ]
