# Generated by Django 3.0.4 on 2020-04-12 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0007_auto_20200412_1936'),
        ('company', '0003_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='selected',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='influencer.Influencer'),
        ),
        migrations.CreateModel(
            name='Interests_for_job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('influencer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='influencer.Influencer')),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.Job')),
            ],
        ),
    ]
